/* LPC804 PLU setup file, generated by 'pluc' */
#include <stdint.h>

void plu(void)
{
	*(uint32_t *)0x40048084UL |= (1UL<<5);   /* Enable PLU Clock */
	*(uint32_t *)0x4004808CUL &= ~(1UL<<5);   /* Reset PLU */
	*(uint32_t *)0x4004808CUL |= (1UL<<5);   /* Clear Reset PLU */
	*(uint32_t *)0x40048080UL |= (1UL<<6);   /* Enable GPIO0 Clock */
	*(uint32_t *)0x40048088UL &= ~(1UL<<6);   /* Reset GPIO0 */
	*(uint32_t *)0x40048088UL |= (1UL<<6);   /* Clear Reset GPIO0 */
	*(uint32_t *)0x40048080UL |= (1UL<<7);   /* Enable SWM Clock */
	*(uint32_t *)0x40048088UL &= ~(1UL<<7);   /* Reset SWM */
	*(uint32_t *)0x40048088UL |= (1UL<<7);   /* Clear Reset SWM */
	*(uint32_t *)0x40048080UL |= (1UL<<18);   /* Enable IOCON Clock */
	*(uint32_t *)0x40048088UL &= ~(1UL<<18);   /* Reset IOCON */
	*(uint32_t *)0x40048088UL |= (1UL<<18);   /* Clear Reset IOCON */
	*(uint32_t *)0x40044018UL &= ~(3UL<<3);    /* PIO0_2 IOCON: Clear mode */
	*(uint32_t *)0x40044018UL |= (2UL<<3);    /* PIO0_2 IOCON: Enable pull-up */
	*(uint32_t *)0xA0002400UL |= (1UL<<2);    /* PIO0_2 GPIO DIRCLRP: Setup as input */
	*(uint32_t *)0x40044014UL &= ~(3UL<<3);    /* PIO0_3 IOCON: Clear mode */
	*(uint32_t *)0x40044014UL |= (2UL<<3);    /* PIO0_3 IOCON: Enable pull-up */
	*(uint32_t *)0xA0002400UL |= (1UL<<3);    /* PIO0_3 GPIO DIRCLRP: Setup as input */
	*(uint32_t *)0x40044038UL &= ~(3UL<<3);    /* PIO0_8 IOCON: Clear mode */
	*(uint32_t *)0x40044038UL |= (2UL<<3);    /* PIO0_8 IOCON: Enable pull-up */
	*(uint32_t *)0xA0002400UL |= (1UL<<8);    /* PIO0_8 GPIO DIRCLRP: Setup as input */
	*(uint32_t *)0x40044034UL &= ~(3UL<<3);    /* PIO0_9 IOCON: Clear mode */
	*(uint32_t *)0x40044034UL |= (2UL<<3);    /* PIO0_9 IOCON: Enable pull-up */
	*(uint32_t *)0xA0002400UL |= (1UL<<9);    /* PIO0_9 GPIO DIRCLRP: Setup as input */
	*(uint32_t *)0xA0002380UL |= (1UL<<23);    /* PIO0_23 GPIO DIRSETP: Setup as output */
	*(uint32_t *)0x4004406cUL &= ~(3UL<<3);    /* PIO0_23 IOCON: Clear mode, deactivate any pull-up/pulldown */
	*(uint32_t *)0xA0002380UL |= (1UL<<24);    /* PIO0_24 GPIO DIRSETP: Setup as output */
	*(uint32_t *)0x40044068UL &= ~(3UL<<3);    /* PIO0_24 IOCON: Clear mode, deactivate any pull-up/pulldown */
	*(uint32_t *)0xA0002380UL |= (1UL<<25);    /* PIO0_25 GPIO DIRSETP: Setup as output */
	*(uint32_t *)0x40044064UL &= ~(3UL<<3);    /* PIO0_25 IOCON: Clear mode, deactivate any pull-up/pulldown */
	*(uint32_t *)0xA0002380UL |= (1UL<<26);    /* PIO0_26 GPIO DIRSETP: Setup as output */
	*(uint32_t *)0x40044054UL &= ~(3UL<<3);    /* PIO0_26 IOCON: Clear mode, deactivate any pull-up/pulldown */
	*(uint32_t *)0x4004405cUL &= ~(3UL<<3);    /* PIO0_30 IOCON: Clear mode */
	*(uint32_t *)0x4004405cUL |= (2UL<<3);    /* PIO0_30 IOCON: Enable pull-up */
	*(uint32_t *)0xA0002400UL |= (1UL<<30);    /* PIO0_30 GPIO DIRCLRP: Setup as input */
	/* LUT 0 Config Value */
	/* PIO0_3 PIO0_2 FF0 FF1|FF0 */
	/* 0-11|1 */
	/* 1-10|1 */
	/* -000|1 */
	/* -101|1 */
	*(uint32_t *)0x40028800 = 0x00005ca3UL; /*PLU*/
	/* LUT 1 Config Value */
	/* PIO0_3 PIO0_2 FF0 FF1|FF1 */
	/* 0-11|1 */
	/* 0-01|1 */
	/* -0-1|1 */
	/* 00--|1 */
	*(uint32_t *)0x40028804 = 0x00007711UL; /*PLU*/
	/* LUT 2 Config Value */
	/* PIO0_8 PIO0_9 FF2 FF3|FF2 */
	/* 0-11|1 */
	/* 1-10|1 */
	/* -000|1 */
	/* -101|1 */
	*(uint32_t *)0x40028808 = 0x00005ca3UL; /*PLU*/
	/* LUT 3 Config Value */
	/* PIO0_8 PIO0_9 FF2 FF3|FF3 */
	/* 0-11|1 */
	/* 0-01|1 */
	/* -0-1|1 */
	/* 00--|1 */
	*(uint32_t *)0x4002880c = 0x00007711UL; /*PLU*/
	/* LUT 4 Config Value */
	/* PIO0_8 PIO0_9 FF2 FF3|PIO0_23 */
	/* 0-01|1 */
	/* 1-00|1 */
	/* -010|1 */
	/* -111|1 */
	*(uint32_t *)0x40028810 = 0x0000c53aUL; /*PLU*/
	/* LUT 5 Config Value */
	/* PIO0_8 PIO0_9 FF3|PIO0_24 */
	/* 001|1 */
	*(uint32_t *)0x40028814 = 0x00000010UL; /*PLU*/
	/* LUT 6 Config Value */
	/* PIO0_3 PIO0_2 FF0 FF1|PIO0_25 */
	/* 0-01|1 */
	/* 1-00|1 */
	/* -010|1 */
	/* -111|1 */
	*(uint32_t *)0x40028818 = 0x0000c53aUL; /*PLU*/
	/* LUT 7 Config Value */
	/* PIO0_3 PIO0_2 FF1|PIO0_26 */
	/* 001|1 */
	*(uint32_t *)0x4002881c = 0x00000010UL; /*PLU*/
	/* PIO0_8 --> PLUINPUT0 */
	*(uint32_t *)0x4000c180 &= ~0x00000003UL; *(uint32_t *)0x4000c180 |= 0x00000001UL; /*SWM*/
	/* PIO0_9 --> PLUINPUT1 */
	*(uint32_t *)0x4000c180 &= ~0x0000000cUL; *(uint32_t *)0x4000c180 |= 0x00000004UL; /*SWM*/
	/* PIO0_2 --> PLUINPUT2 */
	*(uint32_t *)0x4000c180 &= ~0x00000030UL; *(uint32_t *)0x4000c180 |= 0x00000000UL; /*SWM*/
	/* PIO0_3 --> PLUINPUT3 */
	*(uint32_t *)0x4000c180 &= ~0x000000c0UL; *(uint32_t *)0x4000c180 |= 0x00000000UL; /*SWM*/
	/* PLUOUT0 --> PIO0_23 */
	*(uint32_t *)0x4000c180 &= ~0x00003000UL; *(uint32_t *)0x4000c180 |= 0x00002000UL; /*SWM*/
	/* PLUOUT1 --> PIO0_24 */
	*(uint32_t *)0x4000c180 &= ~0x0000c000UL; *(uint32_t *)0x4000c180 |= 0x00008000UL; /*SWM*/
	/* PLUOUT2 --> PIO0_25 */
	*(uint32_t *)0x4000c180 &= ~0x00030000UL; *(uint32_t *)0x4000c180 |= 0x00020000UL; /*SWM*/
	/* PLUOUT3 --> PIO0_26 */
	*(uint32_t *)0x4000c180 &= ~0x000c0000UL; *(uint32_t *)0x4000c180 |= 0x00080000UL; /*SWM*/
	/* LUT4 --> PLUOUT0 */
	*(uint32_t *)0x40028c00 = 0x00000004UL; /*PLU*/
	/* PLUINPUT3 --> LUT0_INP0 */
	*(uint32_t *)0x40028000 = 0x00000003UL; /*PLU*/
	/* PLUINPUT2 --> LUT0_INP1 */
	*(uint32_t *)0x40028004 = 0x00000002UL; /*PLU*/
	/* FF0 --> LUT0_INP2 */
	*(uint32_t *)0x40028008 = 0x00000020UL; /*PLU*/
	/* FF1 --> LUT0_INP3 */
	*(uint32_t *)0x4002800c = 0x00000021UL; /*PLU*/
	/* PLUINPUT3 --> LUT1_INP0 */
	*(uint32_t *)0x40028020 = 0x00000003UL; /*PLU*/
	/* PLUINPUT2 --> LUT1_INP1 */
	*(uint32_t *)0x40028024 = 0x00000002UL; /*PLU*/
	/* FF0 --> LUT1_INP2 */
	*(uint32_t *)0x40028028 = 0x00000020UL; /*PLU*/
	/* FF1 --> LUT1_INP3 */
	*(uint32_t *)0x4002802c = 0x00000021UL; /*PLU*/
	/* PLUINPUT0 --> LUT2_INP0 */
	*(uint32_t *)0x40028040 = 0x00000000UL; /*PLU*/
	/* PLUINPUT1 --> LUT2_INP1 */
	*(uint32_t *)0x40028044 = 0x00000001UL; /*PLU*/
	/* FF2 --> LUT2_INP2 */
	*(uint32_t *)0x40028048 = 0x00000022UL; /*PLU*/
	/* FF3 --> LUT2_INP3 */
	*(uint32_t *)0x4002804c = 0x00000023UL; /*PLU*/
	/* PLUINPUT0 --> LUT3_INP0 */
	*(uint32_t *)0x40028060 = 0x00000000UL; /*PLU*/
	/* PLUINPUT1 --> LUT3_INP1 */
	*(uint32_t *)0x40028064 = 0x00000001UL; /*PLU*/
	/* FF2 --> LUT3_INP2 */
	*(uint32_t *)0x40028068 = 0x00000022UL; /*PLU*/
	/* FF3 --> LUT3_INP3 */
	*(uint32_t *)0x4002806c = 0x00000023UL; /*PLU*/
	/* PLUINPUT0 --> LUT4_INP0 */
	*(uint32_t *)0x40028080 = 0x00000000UL; /*PLU*/
	/* PLUINPUT1 --> LUT4_INP1 */
	*(uint32_t *)0x40028084 = 0x00000001UL; /*PLU*/
	/* FF2 --> LUT4_INP2 */
	*(uint32_t *)0x40028088 = 0x00000022UL; /*PLU*/
	/* FF3 --> LUT4_INP3 */
	*(uint32_t *)0x4002808c = 0x00000023UL; /*PLU*/
	/* PLUINPUT0 --> LUT5_INP0 */
	*(uint32_t *)0x400280a0 = 0x00000000UL; /*PLU*/
	/* PLUINPUT1 --> LUT5_INP1 */
	*(uint32_t *)0x400280a4 = 0x00000001UL; /*PLU*/
	/* FF3 --> LUT5_INP2 */
	*(uint32_t *)0x400280a8 = 0x00000023UL; /*PLU*/
	/* LUT5 --> PLUOUT1 */
	*(uint32_t *)0x40028c04 = 0x00000005UL; /*PLU*/
	/* PLUINPUT3 --> LUT6_INP0 */
	*(uint32_t *)0x400280c0 = 0x00000003UL; /*PLU*/
	/* PLUINPUT2 --> LUT6_INP1 */
	*(uint32_t *)0x400280c4 = 0x00000002UL; /*PLU*/
	/* FF0 --> LUT6_INP2 */
	*(uint32_t *)0x400280c8 = 0x00000020UL; /*PLU*/
	/* FF1 --> LUT6_INP3 */
	*(uint32_t *)0x400280cc = 0x00000021UL; /*PLU*/
	/* LUT6 --> PLUOUT2 */
	*(uint32_t *)0x40028c08 = 0x00000006UL; /*PLU*/
	/* PLUINPUT3 --> LUT7_INP0 */
	*(uint32_t *)0x400280e0 = 0x00000003UL; /*PLU*/
	/* PLUINPUT2 --> LUT7_INP1 */
	*(uint32_t *)0x400280e4 = 0x00000002UL; /*PLU*/
	/* FF1 --> LUT7_INP2 */
	*(uint32_t *)0x400280e8 = 0x00000021UL; /*PLU*/
	/* LUT7 --> PLUOUT3 */
	*(uint32_t *)0x40028c0c = 0x00000007UL; /*PLU*/
	/* LUT0 --> FF0 */
	/* LUT1 --> FF1 */
	/* LUT2 --> FF2 */
	/* LUT3 --> FF3 */
	/* PIO0_30 --> PLU_CLKIN */
	*(uint32_t *)0x4000c01c &= ~0xff000000UL; *(uint32_t *)0x4000c01c |= 0x1e000000UL; /*SWM*/
	/* CLKOUT --> PIO0_30 */
	*(uint32_t *)0x4000c014 &= ~0xff000000UL; *(uint32_t *)0x4000c014 |= 0x1e000000UL; /*SWM*/
	/* CLKOUT clock source select register: Select main clock */
	*(uint32_t *)0x400480F0UL = 1;  /*SYSCON CLKOUTSEL*/
	/* CLKOUT clock divider register: Divide by 2 */
	*(uint32_t *)0x400480F4UL = 2;  /*SYSCON CLKOUTDIV*/
}
