/* 
 * This file was generated by the PLU Config Tool.
 * 6 Inputs 26 LUTs 4 flip flops and 8 outputs */

/* LUT0 (LUT0) */
PLU->LUT[0].INP[0] = 0x00000003; /* IN3 (a0_IN3) */
PLU->LUT[0].INP[1] = 0x00000002; /* IN2 (b0_IN2) */
PLU->LUT[0].INP[2] = 0x00000020; /* FF0 (FF0) */
PLU->LUT[0].INP[3] = 0x00000021; /* FF1 (FF1) */
PLU->LUT[0].INP[4] = 0x0000003F; /* default */
PLU->LUT_TRUTH[0] = 0x5ca35ca3; /* LUT0 (LUT0) CUSTOM */

/* LUT1 (LUT1) */
PLU->LUT[1].INP[0] = 0x00000003; /* IN3 (a0_IN3) */
PLU->LUT[1].INP[1] = 0x00000002; /* IN2 (b0_IN2) */
PLU->LUT[1].INP[2] = 0x00000020; /* FF0 (FF0) */
PLU->LUT[1].INP[3] = 0x00000021; /* FF1 (FF1) */
PLU->LUT[1].INP[4] = 0x0000003F; /* default */
PLU->LUT_TRUTH[1] = 0x77117711; /* LUT1 (LUT1) CUSTOM */

/* LUT2 (LUT2) */
PLU->LUT[2].INP[0] = 0x00000000; /* IN0 (a1_IN0) */
PLU->LUT[2].INP[1] = 0x00000001; /* IN1 (b1_IN1) */
PLU->LUT[2].INP[2] = 0x00000022; /* FF2 (FF2) */
PLU->LUT[2].INP[3] = 0x00000023; /* FF3 (FF3) */
PLU->LUT[2].INP[4] = 0x0000003F; /* default */
PLU->LUT_TRUTH[2] = 0x5ca35ca3; /* LUT2 (LUT2) CUSTOM */

/* LUT3 (LUT3) */
PLU->LUT[3].INP[0] = 0x00000000; /* IN0 (a1_IN0) */
PLU->LUT[3].INP[1] = 0x00000001; /* IN1 (b1_IN1) */
PLU->LUT[3].INP[2] = 0x00000022; /* FF2 (FF2) */
PLU->LUT[3].INP[3] = 0x00000023; /* FF3 (FF3) */
PLU->LUT[3].INP[4] = 0x0000003F; /* default */
PLU->LUT_TRUTH[3] = 0x77117711; /* LUT3 (LUT3) CUSTOM */

/* LUT4 (LUT4) */
PLU->LUT[4].INP[0] = 0x00000000; /* IN0 (a1_IN0) */
PLU->LUT[4].INP[1] = 0x00000001; /* IN1 (b1_IN1) */
PLU->LUT[4].INP[2] = 0x00000022; /* FF2 (FF2) */
PLU->LUT[4].INP[3] = 0x00000023; /* FF3 (FF3) */
PLU->LUT[4].INP[4] = 0x0000003F; /* default */
PLU->LUT_TRUTH[4] = 0xc53ac53a; /* LUT4 (LUT4) CUSTOM */

/* LUT5 (LUT5) */
PLU->LUT[5].INP[0] = 0x00000000; /* IN0 (a1_IN0) */
PLU->LUT[5].INP[1] = 0x00000001; /* IN1 (b1_IN1) */
PLU->LUT[5].INP[2] = 0x00000023; /* FF3 (FF3) */
PLU->LUT[5].INP[3] = 0x0000003F; /* default */
PLU->LUT[5].INP[4] = 0x0000003F; /* default */
PLU->LUT_TRUTH[5] = 0x10101010; /* LUT5 (LUT5) CUSTOM */

/* LUT6 (LUT6) */
PLU->LUT[6].INP[0] = 0x00000003; /* IN3 (a0_IN3) */
PLU->LUT[6].INP[1] = 0x00000002; /* IN2 (b0_IN2) */
PLU->LUT[6].INP[2] = 0x00000020; /* FF0 (FF0) */
PLU->LUT[6].INP[3] = 0x00000021; /* FF1 (FF1) */
PLU->LUT[6].INP[4] = 0x0000003F; /* default */
PLU->LUT_TRUTH[6] = 0xc53ac53a; /* LUT6 (LUT6) CUSTOM */

/* LUT7 (LUT7) */
PLU->LUT[7].INP[0] = 0x00000003; /* IN3 (a0_IN3) */
PLU->LUT[7].INP[1] = 0x00000002; /* IN2 (b0_IN2) */
PLU->LUT[7].INP[2] = 0x00000021; /* FF1 (FF1) */
PLU->LUT[7].INP[3] = 0x0000003F; /* default */
PLU->LUT[7].INP[4] = 0x0000003F; /* default */
PLU->LUT_TRUTH[7] = 0x10101010; /* LUT7 (LUT7) CUSTOM */

PLU->OUTPUT_MUX[0] = 0x00000004; /* LUT4 (LUT4) -> dir1_OUT0 */
PLU->OUTPUT_MUX[1] = 0x00000005; /* LUT5 (LUT5) -> cnt1_OUT1 */
PLU->OUTPUT_MUX[2] = 0x00000006; /* LUT6 (LUT6) -> dir0_OUT2 */
PLU->OUTPUT_MUX[3] = 0x00000007; /* LUT7 (LUT7) -> cnt0_OUT3 */
